spring.application.name=SpringBootRestApi

#server.port=9548

spring.datasource.url=jdbc:mysql://localhost:3306/java11
spring.datasource.username=root
spring.datasource.password=Sush@123
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true